ecomapp/urls.py
from django.urls import path, include
from ecomapp import views

urlpatterns = [
	path('',views.IndexView.as_view(), name='index'),
#prodicts url
	path('search/',views.SearchView.as_view(), name = 'search'),
	path('product/<str:slug>', views.ProductDetailView.as_view(),name='product_detail_url'),

#pages url
	path('page/<str:slug>', views.PageView.as_view() , name='page_url'),
	#edit	
	path('page_edit/<str:slug>', views.PageEdit.as_view() , name='page_edit_url'),
#orders url
	path('order/', views.CreateOrder.as_view(),name='create_order_url'),
	path('orders/', views.ListOrder.as_view(),name='order_list_url'),
	path('order/show/<int:id>', views.OrderDetailView.as_view(),name='order_detail_url'),
	#add product in order
	path('order/add/product/order=<int:id>', views.add_product_in_order,name='add_product_in_order_url'),
	path('order/add_product/category/<str:slug>', views.OrderCategoryView.as_view(), name='add_order_category_url'),
	path('order/add_product', views.OrderIndexView.as_view(), name='add_order_index_url'),
	path('order/add/cart/', views.OrderCartView.as_view(),name='order_cart_url'),
	path('order/add/save/', views.save_order, name='save_order_url'),
	path('order/add/product/<str:slug>',views.OrderProductDetailView.as_view(),name='order_product_detail_url'),
#	path('order/cart/add/<str:slug>', views.add_to_order_cart,name='add_order_to_cart_url'),
	
	#edit 	
	path('order/remove/<int:id>/<int:item_id>',views.remove_product_order,name='remove_product_order_url'),
	path('order/add/<int:id>/<int:item_id>', views.add_product_order,name='add_product_order_url'),
	path('order/minus/<int:id>/<int:item_id>', views.minus_product_order ,name='minus_product_order_url'),

	path('order_finish/',views.OrderFinish.as_view(), name='order_finish_url'),
#carts url
	path('cart/', views.CartView.as_view(),name='cart_url'),
	#edit	
	path('cart/minus/<str:slug>',views.minus_to_cart,name='minus_to_cart_url'),
	path('cart/add/<str:slug>',views.add_to_cart,name='add_to_cart_url'),
	path('cart/remove/<str:slug>',views.remove_from_view,name='remove_from_view_url'),

#categories url
	path('category/<str:slug>',views.CategoryView.as_view(), name='category_list_url' ),
	#edit	
	path('edit_categories/',views.CategoriesEditView.as_view(),name='edit_categories_url'),
]

svitlana_chit/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('ecomapp.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomapp/models.py
from django.db import models

from django.shortcuts import reverse

from django.utils.text import slugify
from transliterate import translit

from django.core.validators import MaxValueValidator, MinValueValidator

from decimal import Decimal
# Create your models here.

class Category(models.Model):
	name = models.CharField(max_length=50, verbose_name = 'Назва')
	slug = models.SlugField(blank=True,verbose_name="Ключове слово(не обов'ясково)")

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('category_list_url',kwargs={'slug':self.slug})

	def save(self, *args, **kwargs):
		if not self.slug and self.name:
			slug = slugify(translit(self.name,'uk', reversed=True))
			self.slug = slug
		super().save( *args, **kwargs)

	class Meta:
		verbose_name = 'Категорію'
		verbose_name_plural = 'Категорії'
		ordering = ['name']
		
class Page(models.Model):

	title = models.CharField(max_length=100, verbose_name='Заголовок')
	description = models.TextField(verbose_name='Опис')
	slug = models.SlugField(verbose_name="Ключове слово")

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('page_url', kwargs={'slug':self.slug})

	def get_edit_url(self):
		return reverse('page_edit_url', kwargs={'slug':self.slug})

	class Meta:
		verbose_name_plural = 'Сторінки сайта'
		verbose_name = 'Сторінку сайта'

def image_folder(instance, filename):
	filename = instance.slug + '.' + filename.split('.')[1]
	return "{0}/{1}".format(instance.slug,filename)

def image_folder_cover(instance, filename):
	filename = instance.slug + '_cover.' + filename.split('.')[-1]
	return "{0}/{1}".format(instance.slug,filename)

def image_folder_album(instance, filename):
	filename = instance.product.slug + '.' + filename.split('.')[-1]
	return "{0}/{1}".format(instance.product.slug, filename)

class Product(models.Model):

	title = models.CharField(max_length=50, verbose_name='Заголовок')
	description = models.TextField( verbose_name='Опис')
	price = models.DecimalField(max_digits=9, decimal_places=2,  verbose_name='Ціна')
	category = models.ForeignKey(Category,on_delete=models.CASCADE, verbose_name='Категорія')
	count = models.PositiveIntegerField(default=1,  verbose_name='Кількість товару')
	slug = models.SlugField(blank=True,  verbose_name="Ключове слово(не обов'ясково)")
	available = models.BooleanField(default=True, verbose_name='В наявності')
	date = models.DateTimeField(auto_now_add=True)
	album_cover = models.ImageField(upload_to=image_folder_cover, verbose_name='Фото обкладинки')

	def get_absolute_url(self):
		return reverse('product_detail_url',kwargs={'slug':self.slug})

	def get_add_order_url(self):
		return reverse('order_product_detail_url',kwargs={'slug':self.slug})

	def delete(self, *args, **kwargs):
		self.album_cover.delete(save=False)
		super().delete(args, kwargs)

	def save(self, *args, **kwargs):
		if not self.slug and self.title:
			slug = slugify(translit(self.title,'uk', reversed=True))
			self.slug = slug
		super().save( *args, **kwargs)

	def get_add_to_cart_url(self):
		return reverse('add_to_cart_url',kwargs={'slug':self.slug})

	def get_add_to_cart_order_url(self):
		return reverse('add_to_cart_url',kwargs={'slug':self.slug})

	def __str__(self):
		return self.title

	class Meta:
		verbose_name = 'Продукт'
		verbose_name_plural = 'Продукти'
		ordering = ['-date']

class Reduction(models.Model):

	title = models.CharField(max_length = 100)
	reduction = models.PositiveSmallIntegerField(default = 1, validators=[
            MaxValueValidator(100),
            MinValueValidator(1)
        ])
	description = models.TextField()
	product = models.ManyToManyField(Product)
	image = models.ImageField(upload_to=image_folder, blank=True, null=True)

	date = models.DateTimeField(auto_now_add = True)

	def __str__(self):
		return "{0}% | {1}".format(str(self.reduction), self.title)

	class Meta:
		verbose_name = 'Знишку'
		verbose_name_plural = 'Знишки'
		ordering = ['-date']

class ProductImage(models.Model):
	
	product = models.ForeignKey(Product, related_name='images',on_delete=models.CASCADE)
	images = models.ImageField(upload_to=image_folder_album )

	def __str__(self):
		return self.images.url

	def delete(self, *args, **kwargs):
		self.images.delete(save=False)
		super().delete(*args,**kwargs)

	class Meta:
		verbose_name = 'фото'
		verbose_name_plural = 'фото'

class CartItem(models.Model):

	product = models.ForeignKey(Product,on_delete=models.CASCADE,verbose_name='Продукт')
	qty = models.PositiveIntegerField(default=1,verbose_name='Назва')
	item_total = models.DecimalField(max_digits=9,decimal_places=2,default=0,blank=True,verbose_name="Сума(необов'язково, рахує самостійно)")

	def __str__(self):
		return "{0} Cart item for product {1}".format(self.id,self.product.title)

	def minus_qty(self):
		if self.qty > 1:
			self.qty -= 1
			self.item_total = self.qty * self.product.price
		self.save()
	
	
	def add_qty(self):
		if self.qty + 1 <= self.product.count:
			self.qty += 1
			self.item_total = self.qty * self.product.price
		self.save()

	def save(self, *args, **kwargs):
		if not self.item_total:
			self.item_total = self.qty * self.product.price 
		super().save( *args, **kwargs)

def sum_items(elements,save = True):
	total_price = Decimal(0.00)
	for item in elements:
		total_price = total_price + item.item_total
	return total_price

class Cart(models.Model):

	item = models.ManyToManyField(CartItem, blank=True)
	cart_total = models.DecimalField(max_digits=9,decimal_places=2,default=0)

	def __str__(self):
		return str(self.id)

	def add_to_cart(self,slug):
		product = Product.objects.get(slug=slug)
		new_item = CartItem.objects.get_or_create(product=product,item_total=product.price)[0]
		els = list(self.item.all())
		if new_item not in els:
			self.item.add(new_item)
			els.append(new_item)
#		print(els)
		self.set_sum(sum_items(els))


	def remove_product_cart(self,slug):
		product = Product.objects.get(slug=slug)
		els = list(self.item.all())
		for item in els:
			if item.product == product:
				self.item.remove(item)
				item.delete()
				els.remove(item)
#		print(els)
		self.set_sum(sum_items(els))

	def get_qty(self):
		return str(self.item.count())

	def set_sum(self,sum, save=True):
		self.cart_total = sum
		if save:
			self.save()

class Order(models.Model):
# Accepted in processing = AIP_status, 'Прийнятий в обробку'
# In processing = IP_status, 'В обробці'
# Paid = PAID_status, 'Оплачено'

	ORDER_STATUS_CHOICES = (
		('AIP_status', 'Прийнятий в обробку'),
		('IP_status', 'В обробці'),
		('PAID_status', 'Оплачено'),
	)

	DELIVERY_STATUS = (
		('nova_poshta', 'Нова пошта'),
		('ukr_poshta', 'Укр-пошта'),
	)
	# cart = models.ForeignKey(Cart,on_delete=models.CASCADE, verbose_name='Корзина')
	products = models.ManyToManyField(CartItem, verbose_name='Товари')
	total = models.DecimalField(max_digits=9, decimal_places=2, default = 0, verbose_name="Сума(необов'язково, рахує самостійно)",blank=True)
	second_name = models.CharField(max_length=200, verbose_name='Прізвище')
	first_name = models.CharField(max_length=200, verbose_name='Імя')
	last_name = models.CharField(max_length=200, verbose_name='Побатькові')
	phone_number = models.CharField(max_length=9, verbose_name='Номер телефону +380')
	email = models.EmailField(blank = True, verbose_name='Електрона пошта')
	buying_type = models.CharField(max_length=40,choices=DELIVERY_STATUS, verbose_name='Спосіб доставки')
	address = models.CharField(max_length=255, verbose_name='адреса')
	status = models.CharField(max_length=100, choices=ORDER_STATUS_CHOICES,default='AIP_status', verbose_name='Статус')
	comments = models.TextField(blank = True, verbose_name='Коментарь')
	date = models.DateTimeField(auto_now_add=True)


	def get_admin_url(self):
		return reverse('order_detail_url',kwargs={'id':self.id})
	    
	def save(self, *args, **kwargs):
		super().save( *args, **kwargs)
		for item in self.products.all():
			if item.product.count - item.qty < 1:
				item.product.count = 0
				item.product.available = False
			else:
				item.product.count -= item.qty
			item.product.save()

	def add_product_order(self,item_id):
		C_item = CartItem.objects.get(id=item_id)
		els = list(self.products.all())
		for item in els:
			if item == C_item:
				item.add_qty()
				break
		self.set_sum(sum_items(els))

	def minus_product_order(self,item_id):
		C_item = CartItem.objects.get(id=item_id)
		els = list(self.products.all())
		for item in self.products.all():
			if item == C_item:
				item.minus_qty()
				break
		self.set_sum(sum_items(els))
	
	def delete(self, *args, **kwargs):
		for item in self.products.all():
			item.delete()
		super().delete(*args, **kwargs)

	def remove_product_order(self,item_id):
		C_item = CartItem.objects.get(id=item_id)
		els = list(self.products.all())
		for item in els:
			if item == C_item:
				self.products.remove(item)
				els.remove(item)
				break
		C_item.delete()
		self.set_sum(sum_items(els))

	def products_add(self,cart):
		self.save()
		for item in cart.item.all():
			new_item = CartItem(product=item.product,qty=item.qty,item_total=item.item_total)
			new_item.save()
			item.delete()
			self.products.add(new_item.id)
		self.save()
		cart.delete()

	def set_sum(self, sum,save = True):
		self.total = sum
		if save:
			self.save()

	def __str__(self):
		return "{} /ДАТА: {} /ПІБ: {} {} {}".format(str(self.id), str(self.date.strftime("%d-%B-%Y")), self.second_name,self.first_name, self.last_name)

	def get_absolute_url(self):
		return reverse('order_detail_url',kwargs={'id':self.id})

	def get_add_product_in_order(self):
		return reverse('add_product_in_order_url',kwargs={'id':self.id})

	class Meta:
		ordering = ['-date']
		verbose_name = 'Замовлення'
		verbose_name_plural = 'Замовлення'

ecomapp/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils import timezone
from ecomapp.models import Order, Page, Category
from django_summernote.widgets import SummernoteWidget

class PageEditForm(forms.ModelForm):
	class Meta:
		model = Page
		fields = ['description']
		widgets = {
			'description' : SummernoteWidget(),
		}

class CategoryForm(forms.ModelForm):
	class Meta:
		model = Category
		fields = ['name']

class OrderForm(forms.ModelForm):

	class Meta:
		model = Order
		fields = ['second_name','first_name','last_name','phone_number','email','buying_type','address','comments']
		labels = {
			"email": "електрона пошта(необов'ясково, для підписки на вигідні пропозиції)"
		}

ecomapp/templates/ecomapp/cart.html
{% extends 'base.html' %}

{% block title %}
Кошик 
{% endblock %}

{% block content %}

<div class="row">
	<div class="col-12">
		<h3>Ваша корзина</h3>
		{% if cart.item.count > 0 %}
		<table class="table table-bordered">
		  <thead>
		    <tr>
		      <th scope="col">Продукт</th>
		      <th scope="col">Кількість</th>
		      <th scope="col">ціна</th>
		      <th scope="col"></th>
		    </tr>
		  </thead>
		  <tbody>
		    {% for item in cart.item.all %}
		    
		    <tr>
		      <th scope="row">
		      	<a style="text-decoration: none; color: #323" href="{{ item.product.get_absolute_url }}">
			      	<img src="{{ item.product.album_cover.url }}" height="40" alt="{{ item.product.slug }}" >
		      		<h4 >{{ item.product.title }}</h4>
		      	</a>
		  	</th>
		      <td>
<a class="btn btn-light" href="{% url 'minus_to_cart_url' slug=item.product.slug %}"><</a>
		      {{ item.qty }}
<a class="btn btn-light" href="{{ item.product.get_add_to_cart_url }}">></a>
		  </td>
		      <td>{{ item.item_total }} грн</td>
		      <td><a class="btn btn-danger" href="{% url 'remove_from_view_url' slug=item.product.slug %}">вилучити з корзини</a></td>
		    </tr>

		    {% endfor %}

		    <tr>
		      <th></th>
		      <td scope="row">всього</td>
		      <td scope="row">{{ cart.cart_total }} грн</td>
		      
		      <td></td>
		    </tr>
		  </tbody>

		</table>
	<div class="col-12">
		<a class="float-right btn btn-primary" href="{% url 'create_order_url' %}">Оформити Замовлення</a>
	</div>
		{% else %}
		<p>Пуста</p>
		<a href="{% url 'index' %}">Продовжити покупки</a>
		{% endif %}
	
	</div>
</div>
	
{% endblock %}

ecomapp/templates/ecomapp/edit_categories.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Редактор Категорій - {{block.super}}
{% endblock %}

{% block other %}
	
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
	  	<li  class="breadcrumb-item">Редактор категорій </li>
	  </ol>
	</nav>

{% endblock %}

{% block content %}
	<div class="row my-3">
		<div class="col-md-5">
			<h3 class="col-12">Категорії</h3>
		{% for category in categories %}
			<p>
				{{category.name}}
				<a href="{% url 'admin:ecomapp_category_change' object_id=category.id %}" target="_blank"і>
					<img width="20" height="20" src="{% static 'img/edit.png' %}">перейменувати 
				</a>
				<a href="{% url 'admin:ecomapp_category_delete' object_id=category.id %}" target="_blank">
					<img width="20" height="20" src="{% static 'img/edit.png' %}">видалити
				</a>
			</p>
		{% endfor %}
		</div>
		<div class="col-md-7">
			<h3 class="col-12">Додати категорію</h3>
			<form method="post" action="{% url 'edit_categories_url' %}" class="form-inline">
			  	{% csrf_token %}
			  <div class="form-group mb-2">
			    {{form.name.label}}
			  </div>
			  <div class="form-group mx-sm-3 mb-2">
			  	{{form.name}}
			  </div>
			  <button type="submit" class="btn btn-primary mb-2">Додати</button>
			</form>
		</div>
	</div>
{% endblock %}

ecomapp/templates/ecomapp/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{ block.super }} - інтернет магазин рукоділля
{% endblock %}

{% block content %}
{{ block.super }}
{% endblock %}

ecomapp/templates/ecomapp/order.html
{% extends 'base.html' %}}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Оформлення замовлення
{% endblock %}

{% block content %}
	<h3>Оформлення замовлення</h3>
	<h4>Ваші покупки</h4>
	{% if cart.item.count > 0 %}
		<table class="table table-bordered">
		  <thead>
		    <tr>
		      <th scope="col">Продукт</th>
		      <th scope="col">Кількість</th>
		      <th scope="col">ціна</th>
		    </tr>
		  </thead>
		  <tbody>
		    {% for item in cart.item.all %}
		    
		    <tr>
		      <th scope="row">
      			<a style="text-decoration: none; color: #323" href="{{ item.product.get_absolute_url }}">
			      	<img src="{{ item.product.album_cover.url }}" height="40" alt="{{ item.product.slug }}" >
		 			{{ item.product.title }}
		      	</a>
		
		      </th>
		      <td>{{ item.qty }}</td>
		      <td>{{ item.item_total }} грн</td>
		    </tr>

		    {% endfor %}
		  </tbody>

		</table>
	<h3><small> Ціна замовлення: </small>{{ cart.cart_total }} грн.</h3>
		{% else %}
		<p>У вас нема покупок.</p>
	<a href="{{request.META.HTTP_REFERER}}">Продовжити покупки</a>
		{% endif %}

	<form action="{% url 'create_order_url'  %}" method="post">
		{% csrf_token %}
		{% for field in form %}
			<div class="form-group">
			{% if field.errors %}
			<div class="alert alert-danger">
				{{field.errors}}
			</div>
			{% endif %}
			  <div class="form-group row">
			    <label class="col-sm-2 col-form-label">{{ field.label }}</label>
			    <div class="col-sm-10">
						{{ field }}
				</div>
			  </div>

			</div>
		{% endfor %}
		<div class="form-group">
			<button type="submit" class="btn btn-success">Завершити</button>
		</div>
	</form>
{% endblock %}

ecomapp/templates/ecomapp/order_cart.html
{% extends 'base_order.html' %}

{% block title %}
Кошик 
{% endblock %}

{% block content %}

<div class="row">
	<div class="col-12">
		<h3>Ваша корзина</h3>
		{% if cart_order.item.count > 0 %}
		<table class="table table-bordered">
		  <thead>
		    <tr>
		      <th scope="col">Продукт</th>
		      <th scope="col">Кількість</th>
		      <th scope="col">ціна</th>
		      <th scope="col"></th>
		    </tr>
		  </thead>
		  <tbody>
		    {% for item in cart_order.item.all %}
		    
		    <tr>
		      <th scope="row">
		      	<a style="text-decoration: none; color: #323" href="{{ item.product.get_add_order_url }}">
			      	<img src="{{ item.product.album_cover.url }}" height="40" alt="{{ item.product.slug }}" >
		      		<h4 >{{ item.product.title }}</h4>
		      	</a>
		  	</th>
		      <td>
<a class="btn btn-light" href="{% url 'minus_to_cart_url' slug=item.product.slug %}"><</a>
		      {{ item.qty }}
<a class="btn btn-light" href="{{ item.product.get_add_to_cart_url }}">></a>
		  </td>
		      <td>{{ item.item_total }} грн</td>
		      <td><a class="btn btn-danger" href="{% url 'remove_from_view_url' slug=item.product.slug %}">вилучити з корзини</a></td>
		    </tr>

		    {% endfor %}

		    <tr>
		      <th></th>
		      <td scope="row">всього</td>
		      <td scope="row">{{ cart_order.cart_total }} грн</td>
		      
		      <td></td>
		    </tr>
		  </tbody>

		</table>
	<div class="col-12">
		<a class="float-right btn btn-primary" href="{% url 'save_order_url' %}">Зберехти зміни</a>
	</div>
		{% else %}
		<p>Пуста</p>
		<a href="{% url 'add_order_index_url' %}">Продовжити покупки</a>
		{% endif %}
	
	</div>
</div>
	
{% endblock %}

ecomapp/templates/ecomapp/order_detail.html
{% extends 'base.html' %}

{% block title %}
Редактор {{page.title}} - {{block.super}}
{% endblock %}

{% block content %}
<div class="row">	
	{% for item in order.products.all %}
		<div class="col-md-3 col-sm-12 ml-1 mb-1 pb-1 border row" > 
			<a href="{{ item.product.get_absolute_url }}">
			<img src="{{ item.product.album_cover.url }}" class="col-12"  alt="{{ item.product.slug }}" >
			<h4 class="col-12">{{ item.product.title }}</h4>
			</a>
			<p class='col-12'>Сума: {{item.item_total}}грн</p>
			<div class="col-12">
				<a class="btn btn-light"  href="{% url 'minus_product_order_url' id=order.id item_id=item.id %}"><</a>
					{{ item.qty }}
				<a class="btn btn-light"  href="{% url 'add_product_order_url' id=order.id item_id=item.id %}">></a>
			</div>
			<div  class='col-12 pt-1'>
				<a href="{% url 'remove_product_order_url' id=order.id item_id=item.id %}" class="btn btn-danger">вилучити з корзини</a>
			</div>
		</div>
   	{% endfor %}
	<div class="col-12">
		<a class="btn btn-primary" href="{{ order.get_add_product_in_order }}">Додати товар</a>
	</div>
</div>

<form action="{{ order.get_absolute_url }}" method="post">
	{% csrf_token %}
		<div class="form-group row">
		    <label class="col-sm-2 col-form-label">Сума(необов'язково, рахує самостійно)</label>
			<div class="col-sm-10">
				<input type="text" name="total" value="{{order.total}}" maxlength="9" required="" id="id_total">грн
			</div>
		</div>
	{% for field in form %}
		<div class="form-group">
			{% if field.errors %}
				<div class="alert alert-danger">
					{{field.errors}}
				</div>
			{% endif %}
			<div class="form-group row">
			    <label class="col-sm-2 col-form-label">{{ field.label }}</label>
				<div class="col-sm-10">
					{{ field }}
				</div>
			</div>
		</div>
	{% endfor %}
	 <button type="submit" class="btn btn-primary mb-2">Зберегти зміни</button>
</form>
<a href="{% url 'order_list_url'%}">перейти до списку</a>
{% endblock %}

ecomapp/templates/ecomapp/order_finish.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Замовлення оформленне - {{ block.super }}
{% endblock %}

{% block content %}
<div class="row w-100">
	<h3 class="col-12">Замовлення оформленне</h3>
	<p class="col-12">Ми приняли замовлення в обробку, очікуйте дзвінок.<br>
	Якщо вже вечір дзвінок, очікуйте вранці.<br>
	Дякуюємо за розумінння.</p>
	<a href="{% url 'index' %}" class="col-12">Продовжити покупки</a>
	<img src="{% static 'img/cell.gif' %}" class="col-md-6 col-sm-12" alt="cell phone">
</div>
{% endblock %}

ecomapp/templates/ecomapp/order_index.html
{% extends 'base_order.html' %}
{% load static %}
{% block title %}
Додати Продукт - {{ block.super }} 
{% endblock %}

{% block other %}
{{ block.super }}
{% endblock %}

{% block content %}
<div class="row justify-content-center">
		<div class="col-md-12">
							<div class="section-title">
								<h2 class="title">{{ title|title }}</h2>
								<div class="pull-right">
									<div class="product-slick-dots-1 custom-dots"></div>
								</div>
							
							</div>
	</div>
{% for product in products %}
	{% include 'ecomapp/includes/product_order_item.html' %}
{% endfor %}
</div>
{% endblock %}

ecomapp/templates/ecomapp/orders.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Список засовленнь - {{ block.super }}
{% endblock %}

{% block content %}

<div class="row">
	<div class="col-12">
		<h3>Ваша корзина</h3>
		<table class="table table-bordered">
		  <thead>
		    <tr>
		      <th scope="col">ПІП</th>
		      <th scope="col">Сума</th>
		      <th scope="col">Номер</th>
		      <th scope="col">Дата</th>
		      <th scope="col">Дії</th>
		    </tr>
		  </thead>
		  <tbody>
		  	  {% for order in orders %}
		  	  
		  	  <tr>
		  	    <th scope="row">
		  	    	{{ order.second_name }} {{ order.first_name }} {{ order.last_name }}
		  		</th>
		  	    <td>{{ order.total }}</td>
		  	    <td>+380 {{ order.phone_number }}</td>
		  	    <td>{{ order.date }}</td>
		  	    <td><a href="{{ order.get_absolute_url }}">Змінити або переглянуть</a>
		  	    </td>
		  	  </tr>

		  	  {% endfor %}

		  	
	  </tbody>

		</table>
	</div>
</div>
{% endblock %}

ecomapp/templates/ecomapp/page.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{page.title}} - {{block.super}}
{% endblock %}

{% block content %}
	
		<h3>{{page.title}}</h3>
		{% if request.user.is_authenticated and request.user.is_staff %}
			<a href="{{ page.get_edit_url }}"><img width="20" height="20" src="{% static 'img/edit.png' %}">редагувати</a>
		{% endif %}
		<p>{{ page.description|safe }}</p>
{% endblock %}

ecomapp/templates/ecomapp/page_edit.html
{% extends 'base.html' %}

{% block title %}
Редактор {{page.title}} - {{block.super}}
{% endblock %}

{% block content %}
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
	  	<li  class="breadcrumb-item">Редактор сторінок </li>
	    <li class="breadcrumb-item active" aria-current="page">редагуем сторінку {{page.title}}</li>
	  </ol>
	</nav>
	<div class="row my-3">

		<h3 class="col-12">{{page.title}}</h3>
		<form action="{{ tag.get_edit_url }}" method="post">
		{% csrf_token %}
		<div class="form-group">
			{% if form.description.errors %}
			<div class="alert alert-danger">
				{{form.description.errors}}
			</div>
			{% endif %}
			
		{{ form.description }}
		  <div class="form-group">
			<button type="submit" class="btn float-right btn-success">Завершити</button>
		</div>
		</form>
	</div>
{% endblock %}